[package]
name = "red-ink"
version = "0.1.0"
authors = ["Jonathan Dahan <hi@jonathan.is>"]
edition = "2018"

[dependencies]
ssd1675 = { git = "https://github.com/jedahan/ssd1675", branch = "yellow" }
websocket = "0.22.2"
